### ISSUE TITLE
spawnSync /bin/sh ENOBUFS is thrown when the POST data is greater than 1 megabytes

### ISSUE THREAD

**Issue by mariotoffia** [Mogztter/unxhr#39]
Hi again and many thanks for this great software! :)

I've stumbled into a problem again. I'm unsure if it is kroki or asciidoc-kroki.  I'm guessing, there's something that I do something incorrect - again...

Cheers,
 Mario :)

I've got the following settings:

```json
"asciidoc.preview.attributes": {
  "kroki-http-method": "post",
  "kroki-max-uri-length":"6000",
  "kroki-fetch-diagram": "true",
  "kroki-server-url": "http://localhost:8000",
  "excalidraw-server-url": "http://localhost:8000",
  "plantuml-server-url": "http://localhost:8000"
}
```
```asciidoc
.Working
[excalidraw]
....
include::storage-encapsulation.json[]
....

.Not working
[excalidraw]
....
include::sample-pipe.json[]
....
```

I've attached a zip file with a working excalidraw (_storage-encapsulation.json_) and the failing one (_sample-pipe.json_).
[excalidraw.zip](https://github.com/Mogztter/asciidoctor-kroki/files/5878123/excalidraw.zip)

The log I get from kroki when doing the failing is the following
```bash
core_1        | {"timestamp":"1611728581739","level":"INFO","thread":"vert.x-eventloop-thread-0","mdc":{"path":"/excalidraw/svg","method":"POST","service_name":"excalidraw","action":"request_received","bytes_read":"41809","user_agent":"node-XMLHttpRequest"},"logger":"io.kroki.server.service.DiagramHandler","message":"Request received POST /excalidraw/svg","context":"default"}
core_1        | {"timestamp":"1611728581739","level":"INFO","thread":"vert.x-eventloop-thread-0","mdc":{"path":"/excalidraw/svg","took":"0","method":"POST","service_name":"excalidraw","action":"convert","file_format":"svg","user_agent":"node-XMLHttpRequest"},"logger":"io.kroki.server.service.DiagramHandler","message":"Convert took 0ms","context":"default"}
```

No svg file is written as meta/assets/diag-uuid.svg.

I'm expecting the following output in the asciidoc preview
![image](https://user-images.githubusercontent.com/1716527/105952287-a7ef9780-6071-11eb-8dd8-8075ed631576.png)

But I get the JSON instead (if it's not working, it usually outputs a broken image)
![image](https://user-images.githubusercontent.com/1716527/105952308-b3db5980-6071-11eb-8a6a-826784251543.png)

**Comment by mariotoffia** [comment]
@Mogztter  again many thanks for your great support! :) I'm using the the docker-compose.xml from kroki.io and I'm guessing it uses [this](https://github.com/yuzutech/kroki/blob/master/excalidraw/Dockerfile#L2) where it declares

```dockerfile
# Package the Node.js project into a single binary
FROM node:12.18.4-alpine3.11 as builder
```

I will track the progress in the unxhr!

Cheers,
 Mario :)

**Comment by Mogztter** [comment]
> again many thanks for your great support! :) I'm using the the docker-compose.xml from kroki.io and I'm guessing it uses this where it declares

I was asking about the version of Node used client-side (by VS Code) to execute the Asciidoctor Kroki extension.
`unxhr` is used to send requests from the client to the server. 

But in any case the limit is too low :wink:

**Comment by mariotoffia** [comment]
Hahahaha sorry about that! :D - vscode is running node v12.14.1...
